### ISSUE TITLE
Repeated license on HTML

### ISSUE THREAD

**Issue by henryyang42** [bruce3557/NTHUOJ_web#103]
I found that we have repeated license on rendered HTML since we use ``extends`` and ``include`` in our templates.
The repeated license is unnecessary and will be a waste.
Maybe we can put it in ``base.html`` only once to prevent that happen.

Any other suggestions?

**Comment by bbiiggppiigg** [comment]
Unless the license file will somehow be changed in the future, I think your suggestion will work fairly well.

**Comment by Changron** [comment]
I think the license should attach to any file. Since the purpose is to say that this file is under the license.

**Comment by henryyang42** [comment]
I think whole project is under the license.
Therefore, some opensource project only place LICENSE on the root of the project.
