### ISSUE TITLE
Suggestion on disabling user login 

### ISSUE THREAD

**Issue by bbiiggppiigg** [bruce3557/NTHUOJ_web#104]
It seems like there is a mechanism of disabling users from login when the wrong combination of username and password are tried too many time, but I think an alert or a warning text marked might fit this purpose better , since a 404 page gives a users no clue of what is actually happening. (BTW  I haven't check the grammar and I hope this is understandable

**Comment by henryyang42** [comment]
I am aware of this. I will redirect it to a proper page in the future.

**Comment by nickelcheng** [comment]
In my opinion, this issue should fixed before 4/9
BTW, how long will an IP be blocked?

**Comment by henryyang42** [comment]
OK, I'll fix it as soon as possible.
The IP will be blocked for 6 minutes.
