### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by nickelcheng** [bruce3557/NTHUOJ_web#108]
1. Problem owner should be auto filled, not filled by user (BTW, an user doesn't have subjudge auth can not be problem owner)
2. Preview tag and actual tag doesn't match
3. Judge type should be listed.
4. Add problem name before add problem
5. Show pid and problem name in edit problem page
6. Remove search bar
7. Add a cancel or back button in edit problem page

**Comment by nickelcheng** [comment]
@geniusgordon please fix the issue

**Comment by geniusgordon** [comment]
pull request sent

**Comment by nickelcheng** [comment]
fix in #112

**Comment by nickelcheng** [comment]
resolved in #112
