### ISSUE TITLE
Contest countdown js bug

### ISSUE THREAD

**Issue by CHIAHSINHOU** [bruce3557/NTHUOJ_web#226]
![2015-09-15 4 14 32](https://cloud.githubusercontent.com/assets/10843493/9871245/e00b7c9a-5bc4-11e5-821c-95cee8c6c95e.png)

It said Contest Not Started Yet but It was started.

**Comment by Changron** [comment]
the timer is based on the footer clock
the problem will be fixed the time #227 fixed
