### ISSUE TITLE
Can add contest. Can show database data

### ISSUE THREAD

**Issue by CHIAHSINHOU** [bruce3557/NTHUOJ_web#54]
![2015-03-05 4 47 05](https://cloud.githubusercontent.com/assets/10843493/6501763/628a1976-c357-11e4-9443-ce2f6a79ea89.png)
我有放題目 可是沒有出來

![2015-03-05 4 40 53](https://cloud.githubusercontent.com/assets/10843493/6501772/719f0fa2-c357-11e4-9b5a-0a951895554a.png)
![2015-03-05 4 40 59](https://cloud.githubusercontent.com/assets/10843493/6501776/78f0a400-c357-11e4-8936-e50b88cb1241.png)
這個字型大小有點差太多了

![2015-03-05 4 42 52](https://cloud.githubusercontent.com/assets/10843493/6501782/85c58a1a-c357-11e4-9959-5f573631de04.png)
cname 是什麼啦 網頁端不要出現像是變數名稱的詞

**Comment by Changron** [comment]
Where does the cname stuff appear?
I think time is important and should be bigger than normal text.
Which should I use if it is too big?
I use <h3> tag now

**Comment by nickelcheng** [comment]
@Changron, does this issue fixed?

**Comment by Changron** [comment]
fixed
