### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Changron** [bruce3557/NTHUOJ_web#57]
![2015-03-07 10 06 36](https://cloud.githubusercontent.com/assets/9431996/6539546/b34833c4-c4b1-11e4-9c08-4219afe3a25e.png)

when creating or editing contest, the footer still block the content.
the footer appears when user is at the bottom of the page, but this will block the content.
Maybe at bottom, the footer should disappear, and at other place, the footer is shown.
The solution two I can think of, is that we can fix the footer right beneath the content. 
So that it won't block in any situation. But this conficts with current design.

**Comment by hydai** [comment]
Well, I want to know that this issue occurs in which branch.
I will test and figure out this problem later.

**Comment by Changron** [comment]
in bruce/dev

**Comment by hydai** [comment]
Your idea is good.
I rewrite the css to fix footer beneath the content.
Please test my latest [commit](https://github.com/hydai/NTHUOJ_web/tree/dev), and give me a feedback whatever it is subject to revision or not.

**Comment by Changron** [comment]
Thanks hydai, it won't block anything now. thanks!
