### ISSUE TITLE
Call validate_user before using user object

### ISSUE THREAD

**Issue by nickelcheng** [bruce3557/NTHUOJ_web#63]

**Comment by henryyang42** [comment]
Another solution is to use ``@login_required`` decorator.
I think this is more elegant and more proper.
``validate_user`` should only be used in some ``utils`` to avoid some missing attributes.
https://docs.djangoproject.com/en/1.7/topics/auth/default/#django.contrib.auth.decorators.login_required

**Comment by nickelcheng** [comment]
@henryyang42
