### ISSUE TITLE
Active link

### ISSUE THREAD

**Issue by CHIAHSINHOU** [bruce3557/NTHUOJ_web#65]
在 install 時產生的 super user 沒有收到 active 的信 沒辦法用

**Comment by henryyang42** [comment]
![2015-03-12 7 31 48](https://cloud.githubusercontent.com/assets/6128538/6620240/a2b52f3c-c90a-11e4-8e35-a1fef53b9797.png)

在patch來之前可以先手動解決

**Comment by henryyang42** [comment]
In #67, I set admin's ``is_active`` to be ``True`` when created.
So, admin don't have to receive activation email anymore. After all, admin is god.
