### ISSUE TITLE
index.js error

### ISSUE THREAD

**Issue by geniusgordon** [bruce3557/NTHUOJ_web#70]
index.js 裡面有 error
好像會影響到我的頁面的javascript

![image](https://cloud.githubusercontent.com/assets/8642924/6656029/8a5881ae-cb54-11e4-800c-66879997f94e.png)

![image](https://cloud.githubusercontent.com/assets/8642924/6656040/0aaa2b3c-cb55-11e4-9f1c-2a906d7d5b53.png)

**Comment by henryyang42** [comment]
@drowsy810301 has fixed that problem in #68.
You can comment that line if it affects your js functionality.

**Comment by geniusgordon** [comment]
ok thanks~
