### ISSUE TITLE
Timer fails on some pages

### ISSUE THREAD

**Issue by henryyang42** [bruce3557/NTHUOJ_web#86]
I notice that on some page the timer will appear NaN.
Can @drowsy810301 figure out why?

http://140.114.77.123:8000/group/list/
http://140.114.77.123:8000/problem/volume/

**Comment by nickelcheng** [comment]
Does this issue fixed?

**Comment by nickelcheng** [comment]
@drowsy810301, @henryyang42 does this issue fixed?

**Comment by henryyang42** [comment]
Use ``render_index`` in ``utils.render_helper`` can fix it.

**Comment by drowsy810301** [comment]
#### Usage:
```
from utils.render_helper import render_index
```
``` render_index ``` replace ``` render ```

**Comment by drowsy810301** [comment]
@Changron @Casmo @geniusgordon @henryyang42  @drowsy810301

**Comment by henryyang42** [comment]
Done. Waiting for reviewing.

**Comment by nickelcheng** [comment]
@drowsy810301, did you resolve this issue in #110 ?

**Comment by drowsy810301** [comment]
Yes
